name = "q2git"
language = "tinygo"
type = "component"
version = "0.1.0"

[component]
wit_world = "hello"
wasm_target = "wasm32-wasip2"
build_command = "cd src && tinygo build -target=wasm32-wasip2 -o ../build/q2git.wasm ."
